DROP TABLE MSC_ENGINE_COMMUNICATION;
CREATE TABLE MSC_ENGINE_COMMUNICATION
(
  REQUEST_ID    NUMBER(18) NOT NULL,
  PLAN_ID       NUMBER(18) NOT NULL,
  PROFILE_ID    NUMBER(18) NOT NULL,
  BRANCH_ID     NUMBER(18) NOT NULL,
  PNAME         VARCHAR2(40),
  PTYPE         VARCHAR2(20),
  VALUE_FLOAT   FLOAT(126),
  VALUE_DATE    DATE,
  VALUE_STRING  VARCHAR2(2000)
);
DESC MSC_ENGINE_COMMUNICATION;
--------------------------------------------------------
--  File created - Sunday-October-21-2012   
--------------------------------------------------------
REM INSERTING into  MSC_ENGINE_COMMUNICATION


BEGIN
   FOR BRANCH_NUMBER IN 1..&1 LOOP

Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'opti_time','date',null,to_date('20-SEP-12','DD-MON-RR'),null);
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'last_date','date',null,to_date('18-SEP-12','DD-MON-RR'),null);
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'start_date','date',null,to_date('01-JAN-95','DD-MON-RR'),null);
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'INIT_PARAMS_NAME','string',null,null,'MSC_PROFILE_ENG_PARAMS_VALUES');
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'IS_SUBSET_PROFILE','float',0,null,null);
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'XMLDirectory','string',null,null,'..\xml\');
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'EngineLogFile','string',null,null,'\engine2k\Engine2k.log');
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'ProcSchemaFile','string',null,null,'engine2000.xml');
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'EngineLogFilterGroups','float',384,null,null);
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'EngGeneralLevel','float',6,null,null);
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'EngineOmitFileName','string',null,null,'Y');
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'EngineOmitTime','string',null,null,'N');
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'EngAnalyticalLevel','float',6,null,null);
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'EngCacheLevel','float',6,null,null);
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'EngDebugProLevel','float',6,null,null);
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'EngDictionariesLevel','float',6,null,null);
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'EngEventsLevel','float',6,null,null);
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'EngFitforecastLevel','float',6,null,null);
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'EngForecastLevel','float',6,null,null);
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'EngMatricesLevel','float',6,null,null);
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'EngMemoryLevel','float',6,null,null);
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'EngNodesLevel','float',6,null,null);
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'EngOptimizationLevel','float',6,null,null);
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'EngOtherLevel','float',6,null,null);
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'EngPTSLevel','float',6,null,null);
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'EngProcessorsLevel','float',6,null,null);
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'EngSQLLevel','float',4,null,null);
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'EngSplitterLevel','float',6,null,null);
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'EngStatisticsLevel','float',6,null,null);
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'EngTreeIteratorLevel','float',6,null,null);
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'EngUserLevel','float',6,null,null);
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'AGroups','string',null,null,null);
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'top_level','float',5,null,null);
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'QueryEngParamsConfig','query',0,null,'SELECT PARAMETER_NAME, PARAMETER_COL_TYPE from MSC_ENG_PARAMETERS_B ');
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'QueryCausalFactorsConfig','query',0,null,'SELECT cfb.CAUSAL_FACTOR_ID,
  UPPER(CAUSAL_FACTOR_DISP_NAME),
  DECODE(LOWER(CAUSAL_TYPE_NAME),''seasonality'',''global'',''baseline volume'',''global'',''trend'',''global'',''price'',''price'',''local''),
  SHORT_METHODS,
  LONG_METHODS,
  MULTI_METHOD_GR1,
  MULTI_METHOD_GR2,
  NON_SEASONAL,
  FILL_MISSING_VALUES,
  SHAPE_DEF,
  0,
  0,
  '' '',
  '' '',
  SCALE_UNEVEN_PERIODS,
  TIME_RELATED 
FROM MSC_PROFILE_CAUSAL_FACTORS_B cfb, 
  MSC_PROFILE_CAUSAL_FACTORS_TL cftl, 
  MSC_CAUSAL_FACTORS_TYPES_TL cfttl 
WHERE cfb.CAUSAL_FACTOR_ID = cftl.CAUSAL_FACTOR_ID and 
      cfb.PLAN_ID = cftl.PLAN_ID and 
      cfb.PROFILE_ID = cftl.PROFILE_ID and 
      cfb.CAUSAL_TYPE_ID = cfttl.CAUSAL_TYPE_ID and 
      cftl.LANGUAGE = cfttl.LANGUAGE and 
      cftl.LANGUAGE = ''US'' and cfb.PLAN_ID = ? and 
      cfb.PROFILE_ID = ? and 
      ( LOWER(CAUSAL_TYPE_NAME) in (''seasonality'',''baseline volume'',''trend'',''price'') OR SHORT_METHODS = 1 OR LONG_METHODS = 1 OR MULTI_METHOD_GR1 = 1 OR MULTI_METHOD_GR2 = 1 OR NON_SEASONAL = 1) 
order by cfb.causal_factor_id ');
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'QueryGlobalCausalsData','query',0,null,'SELECT min(DAY_DATE), min(CONSTANT), min(TREND), min(JANUARY), min(FEBRUARY), min(MARCH), min(APRIL), min(MAY), min(JUNE), min(JULY), min(AUGUST), min(SEPTEMBER), min(OCTOBER), min(NOVEMBER), min(DECEMBER) 
FROM MSC_DM_MOCK_GLOBAL_CAUSALS g, MSC_DM_MOCK_TIME_DIMENSION t
WHERE g.week_id = t.week_id
group by g.week_id
ORDER BY min(DAY_DATE)');
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'QueryAggriSql_1','query',0,null,'SELECT min(DAY_DATE), sum(ACTUAL_QUANTITY) as QUANTITY, min(PRICE), min(ERROR_STD), min(UP_TIME)
FROM
	MSC_DM_MOCK_SALES_DATA        s,
	MSC_DM_MOCK_MDP_MATRIX        m,
	MSC_DM_MOCK_PRODUCT_DIMENSION p,
	MSC_DM_MOCK_ORG_DIMENSION     o,
	MSC_DM_MOCK_TIME_DIMENSION    w
WHERE 
	s.ITEM_ID = m.item_id AND s.ORGANIZATION_ID = m.ORGANIZATION_ID AND s.SITE_ID = m.SITE_ID AND
	s.WEEK_ID = w.WEEK_ID AND 
	m.ITEM_ID = p.ITEM_ID AND 
	m.ORGANIZATION_ID = o.ORGANIZATION_ID AND 
   DAY_DATE >= ? AND DAY_DATE <= ? AND (ACTUAL_QUANTITY IS NOT NULL or DAY_DATE > ? ) AND  
	p.ITEM_ID = ?  AND o.ORGANIZATION_ID = ? 
GROUP BY w.WEEK_ID
ORDER BY w.WEEK_ID');
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'QueryAggriSql_2','query',0,null,'SELECT min(DAY_DATE), sum(ACTUAL_QUANTITY) as QUANTITY, min(PRICE), min(ERROR_STD), min(UP_TIME)
FROM
	MSC_DM_MOCK_SALES_DATA        s,
	MSC_DM_MOCK_MDP_MATRIX        m,
	MSC_DM_MOCK_PRODUCT_DIMENSION p,
	MSC_DM_MOCK_ORG_DIMENSION     o,
	MSC_DM_MOCK_TIME_DIMENSION    w
WHERE 
	s.ITEM_ID = m.item_id AND s.ORGANIZATION_ID = m.ORGANIZATION_ID AND s.SITE_ID = m.SITE_ID AND
	s.WEEK_ID = w.WEEK_ID AND 
	m.ITEM_ID = p.ITEM_ID AND 
	m.ORGANIZATION_ID = o.ORGANIZATION_ID AND 
   DAY_DATE >= ? AND DAY_DATE <= ? AND (ACTUAL_QUANTITY IS NOT NULL or DAY_DATE > ? ) AND  
	p.BRAND_ID = ?  AND o.LEGAL_ENTIRY_ID = ? 
GROUP BY w.WEEK_ID 
ORDER BY w.WEEK_ID');
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'QueryAggriSql_3','query',0,null,'SELECT min(DAY_DATE), sum(ACTUAL_QUANTITY) as QUANTITY, min(PRICE), min(ERROR_STD), min(UP_TIME)
FROM
	MSC_DM_MOCK_SALES_DATA        s,
	MSC_DM_MOCK_MDP_MATRIX        m,
	MSC_DM_MOCK_PRODUCT_DIMENSION p,
	MSC_DM_MOCK_ORG_DIMENSION     o,
	MSC_DM_MOCK_TIME_DIMENSION    w
WHERE 
	s.ITEM_ID = m.item_id AND s.ORGANIZATION_ID = m.ORGANIZATION_ID AND s.SITE_ID = m.SITE_ID AND
	s.WEEK_ID = w.WEEK_ID AND 
	m.ITEM_ID = p.ITEM_ID AND 
	m.ORGANIZATION_ID = o.ORGANIZATION_ID AND 
   DAY_DATE >= ? AND DAY_DATE <= ? AND (ACTUAL_QUANTITY IS NOT NULL or DAY_DATE > ? ) AND  
	p.SEGMENT_ID = ?  AND o.OPERATING_UNIT_ID = ? 
GROUP BY w.WEEK_ID 
ORDER BY w.WEEK_ID');
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'QueryAggriSql_4','query',0,null,'SELECT min(DAY_DATE), sum(ACTUAL_QUANTITY) as QUANTITY,min(PRICE),	min(ERROR_STD), min(UP_TIME)
FROM
	MSC_DM_MOCK_SALES_DATA        s,
	MSC_DM_MOCK_MDP_MATRIX        m,
	MSC_DM_MOCK_PRODUCT_DIMENSION p,
	MSC_DM_MOCK_ORG_DIMENSION     o,
	MSC_DM_MOCK_TIME_DIMENSION    w
WHERE 
	s.ITEM_ID = m.item_id AND s.ORGANIZATION_ID = m.ORGANIZATION_ID AND s.SITE_ID = m.SITE_ID AND
	s.WEEK_ID = w.WEEK_ID AND 
	m.ITEM_ID = p.ITEM_ID AND 
	m.ORGANIZATION_ID = o.ORGANIZATION_ID AND 
   DAY_DATE >= ? AND DAY_DATE <= ? AND (ACTUAL_QUANTITY IS NOT NULL or DAY_DATE > ? ) AND  
	p.CATEGORY_ID = ?  AND o.BUSINESS_GROUP_ID = ? 
GROUP BY w.WEEK_ID
ORDER BY w.WEEK_ID');
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'QueryScan1','query',0,null,'SELECT 1, min(CATEGORY_ID) as CATEGORY_ID, min(BUSINESS_GROUP_ID) as BUSINESS_GROUP_ID, min(SEGMENT_ID) as SEGMENT_ID, min(OPERATING_UNIT_ID) as OPERATING_UNIT_ID, min(BRAND_ID) as BRAND_ID, min(LEGAL_ENTIRY_ID) as LEGAL_ENTIRY_ID, m.ITEM_ID, m.ORGANIZATION_ID, min(glob_prop), min(glob_prop), min(glob_prop), min(glob_prop), min(glob_prop), min(glob_prop), min(glob_prop), min(glob_prop), min(glob_prop), min(glob_prop), min(glob_prop), min(glob_prop), min(glob_prop), 0,0,0,0,0,0,0,0,0,0,0,0,0,0, 0, 0, 1, -1, -1, min(prediction_status), 0, min(FROM_DATE),  	max(TO_DATE), 1 FROM MSC_DM_MOCK_MDP_MATRIX m , MSC_DM_MOCK_PRODUCT_DIMENSION p, MSC_DM_MOCK_ORG_DIMENSION o , ENGINE_BRANCH_LIST b WHERE m.ITEM_ID = b.ITEM AND m.ORGANIZATION_ID = b.LOCATION AND 	m.ITEM_ID = p.ITEM_ID AND m.ORGANIZATION_ID = o.ORGANIZATION_ID AND do_fore = 1 AND (prediction_status = ''1'') AND (m.last_update_date <> ? OR m.last_update_date is NULL) and b.branch_id = ? 
 GROUP BY m.ITEM_ID, m.ORGANIZATION_ID ORDER BY BUSINESS_GROUP_ID,CATEGORY_ID,OPERATING_UNIT_ID,SEGMENT_ID,LEGAL_ENTIRY_ID,BRAND_ID,ORGANIZATION_ID,ITEM_ID');
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'QueryResetForecast','query',0,null,'');
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'QueryModelConfig','query',0,null,'SELECT b.METHOD_CODE, '' '', DECODE(b.METHOD_TYPE_ID,1,''short'',2,''long'',3,''nonseasonal'',4,''daily'',5,''empty''), m.MIN_OBSERVATIONS, m.MAX_OBSERVATIONS, m.IS_SELECTED 
from MSC_PROFILE_METHODS m, MSC_METHODS_B b where m.method_id = b.method_id and plan_id=? and profile_id=?');
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'QueryModelParams','query',0,null,'SELECT m.METHOD_CODE,p.METHOD_PARAM_DEF_VALUE, LTRIM(RTRIM(p.METHOD_PARAM_NAME)),''string'',1
from MSC_METHODS_B m, MSC_METHOD_PARAMS_B p 
where m.METHOD_ID = p.METHOD_ID order by METHOD_CODE');
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'QueryQuantityForSplit','query',0,null,'SELECT s.ITEM_ID, s.ORGANIZATION_ID,	min(DAY_DATE) as DAY_DATE, sum(ACTUAL_QUANTITY) FROM MSC_DM_MOCK_SALES_DATA s ,MSC_DM_MOCK_MDP_MATRIX m ,MSC_DM_MOCK_TIME_DIMENSION w WHERE s.ITEM_ID = m.item_id AND s.ORGANIZATION_ID = m.ORGANIZATION_ID AND s.SITE_ID = m.SITE_ID AND	s.WEEK_ID = w.WEEK_ID AND m.do_fore = 1 AND m.prediction_status = ''1'' AND	DAY_DATE >= ? AND DAY_DATE <= ? GROUP BY s.ITEM_ID, s.ORGANIZATION_ID ORDER BY s.ITEM_ID, s.ORGANIZATION_ID, DAY_DATE');
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'QueryUpdateData','query',0,null,'UPDATE MSC_DM_MOCK_SALES_DATA SET FORECAST = ? , SIG_SQR = ? , REGIME_CHANGE = ?, FORECAST_OUTLIER = ? WHERE ITEM_ID = ? AND ORGANIZATION_ID = ? AND WEEK_ID = (select WEEK_ID from MSC_DM_MOCK_TIME_DIMENSION where DAY_DATE = ?)');
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'QueryUpdateDataFake','query',0,null,'UPDATE MSC_DM_MOCK_SALES_DATA SET FORECAST = NULL, FORECAST_OUTLIER = NULL WHERE ITEM_ID = ? AND ORGANIZATION_ID = ?');
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'QueryUpdateMatrix','query',0,null,'UPDATE MSC_DM_MOCK_MDP_MATRIX set ITEM_ID = ?, ORGANIZATION_ID = ?, OUTLIER = ?, ITEM_NODE = ?, LOC_NODE = ?, LEVEL_ID = ?, LAST_UPDATE_DATE = cast(sysdate as DATE), SALES_DATA_LUD = cast(sysdate as DATE), MODELS = ?, DELMODEL = ?, METRICS_OBS = ?, METRICS_MAPE = ?, METRICS_MRE = ?, METRICS_RMSE = ?, METRICS_PBIAS = ?, BRANCH_ID = ? WHERE ITEM_ID = ? and ORGANIZATION_ID = ?');
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'QueryArrayUpdateData','query',0,null,'MERGE INTO MSC_DM_MOCK_SALES_DATA TRG USING (SELECT MSC_DM_MOCK_SALES_DATA.ITEM_ID AS ITEM_ID ,MSC_DM_MOCK_SALES_DATA.ORGANIZATION_ID AS ORGANIZATION_ID ,MSC_DM_MOCK_SALES_DATA.SITE_ID AS SITE_ID ,MSC_DM_MOCK_SALES_DATA.WEEK_ID AS WEEK_ID ,MSC_DM_MOCK_MDP_MATRIX.GLOB_PROP AS GLOB_PROP ,SUM(MSC_DM_MOCK_MDP_MATRIX.GLOB_PROP) OVER (PARTITION BY MSC_DM_MOCK_SALES_DATA.ITEM_ID, MSC_DM_MOCK_SALES_DATA.ORGANIZATION_ID, MSC_DM_MOCK_SALES_DATA.WEEK_ID) AS SUM_GLOB_PROP ,COUNT(1)  OVER (PARTITION BY MSC_DM_MOCK_SALES_DATA.ITEM_ID, MSC_DM_MOCK_SALES_DATA.ORGANIZATION_ID, MSC_DM_MOCK_SALES_DATA.WEEK_ID) AS ROW_COUNT ,? AS FORECAST ,? AS OUTLIER ,? AS SIG_SQR ,? AS REGIME_CHANGE from MSC_DM_MOCK_MDP_MATRIX join MSC_DM_MOCK_SALES_DATA on MSC_DM_MOCK_MDP_MATRIX.ITEM_ID =  MSC_DM_MOCK_SALES_DATA.ITEM_ID AND MSC_DM_MOCK_MDP_MATRIX.ORGANIZATION_ID = MSC_DM_MOCK_SALES_DATA.ORGANIZATION_ID AND MSC_DM_MOCK_MDP_MATRIX.SITE_ID =  MSC_DM_MOCK_SALES_DATA.SITE_ID and MSC_DM_MOCK_SALES_DATA.item_id = ? and MSC_DM_MOCK_SALES_DATA.organization_id   = ? and MSC_DM_MOCK_SALES_DATA.week_id = (select WEEK_ID from MSC_DM_MOCK_TIME_DIMENSION where DAY_DATE = ?) ) SRC ON (SRC.ITEM_ID = TRG.ITEM_ID AND SRC.ORGANIZATION_ID = TRG.ORGANIZATION_ID AND SRC.SITE_ID = TRG.SITE_ID AND SRC.WEEK_ID = TRG.WEEK_ID) WHEN MATCHED THEN UPDATE SET TRG.LAST_UPDATE_DATE = SYSTIMESTAMP,TRG.FORECAST = (SRC.FORECAST * (CASE WHEN NVL(SRC.SUM_GLOB_PROP, 0) > 0 THEN SRC.GLOB_PROP / SRC.SUM_GLOB_PROP ELSE 1 / SRC.ROW_COUNT END)) ,TRG.FORECAST_OUTLIER = SRC.OUTLIER,TRG.SIG_SQR = SRC.SIG_SQR ,TRG.REGIME_CHANGE = SRC.REGIME_CHANGE');
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'QueryArrayUpdateMatrix','query',0,null,'UPDATE MSC_DM_MOCK_MDP_MATRIX set OUTLIER = ?, ITEM_NODE = ?, LOC_NODE = ?, LEVEL_ID = ?, LAST_UPDATE_DATE = cast(sysdate as DATE), SALES_DATA_LUD = cast(sysdate as DATE), MODELS = ?, DELMODEL = ?, METRICS_OBS = ?, METRICS_MAPE = ?, METRICS_MRE = ?, METRICS_RMSE = ?, METRICS_PBIAS = ?, BRANCH_ID = ? WHERE ITEM_ID = ? and ORGANIZATION_ID = ?');
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'QueryArrayInsertData','query',0,null,'INSERT INTO ENGINE_SALES_OUTPUT (FORECAST,FORECAST_OUTLIER,SIG_SQR,REGIME_CHANGE,LAST_UPDATE_DATE,ITEM_ID,ORGANIZATION_ID,WEEK_ID) values (?,?,?,?,(SELECT cast(SYSDATE as DATE) FROM DUAL),?,?,(select WEEK_ID from MSC_DM_MOCK_TIME_DIMENSION where DAY_DATE = ?))');
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'ForecastTreeLevels.0Item','string',null,null,'@ITEM_ID');
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'ForecastTreeLevels.0Loc','string',null,null,'@ORGANIZATION_ID');
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'ForecastTreeLevels.1Item','string',null,null,'@ITEM_ID');
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'ForecastTreeLevels.1Loc','string',null,null,'@ORGANIZATION_ID');
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'ForecastTreeLevels.2Item','string',null,null,'@BRAND_ID');
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'ForecastTreeLevels.2Loc','string',null,null,'@LEGAL_ENTIRY_ID');
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'ForecastTreeLevels.3Item','string',null,null,'@SEGMENT_ID');
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'ForecastTreeLevels.3Loc','string',null,null,'@OPERATING_UNIT_ID');
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'ForecastTreeLevels.4Item','string',null,null,'@CATEGORY_ID');
Insert into  MSC_ENGINE_COMMUNICATION (REQUEST_ID,PLAN_ID,PROFILE_ID,BRANCH_ID,PNAME,PTYPE,VALUE_FLOAT,VALUE_DATE,VALUE_STRING) values (1,0,300100010946731,BRANCH_NUMBER,'ForecastTreeLevels.4Loc','string',null,null,'@BUSINESS_GROUP_ID');

  END LOOP;
END;
/

SELECT * FROM MSC_ENGINE_COMMUNICATION;

commit;